// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: lospan/lospan.proto

package lospan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LospanClient is the client API for Lospan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LospanClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type lospanClient struct {
	cc grpc.ClientConnInterface
}

func NewLospanClient(cc grpc.ClientConnInterface) LospanClient {
	return &lospanClient{cc}
}

func (c *lospanClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/lospan.Lospan/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LospanServer is the server API for Lospan service.
// All implementations should embed UnimplementedLospanServer
// for forward compatibility
type LospanServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedLospanServer should be embedded to have forward compatible implementations.
type UnimplementedLospanServer struct {
}

func (UnimplementedLospanServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

// UnsafeLospanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LospanServer will
// result in compilation errors.
type UnsafeLospanServer interface {
	mustEmbedUnimplementedLospanServer()
}

func RegisterLospanServer(s grpc.ServiceRegistrar, srv LospanServer) {
	s.RegisterService(&Lospan_ServiceDesc, srv)
}

func _Lospan_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LospanServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lospan.Lospan/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LospanServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lospan_ServiceDesc is the grpc.ServiceDesc for Lospan service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lospan_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lospan.Lospan",
	HandlerType: (*LospanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Lospan_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lospan/lospan.proto",
}
